// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetMultiaddr() {
  return window['go']['app']['App']['GetMultiaddr']();
}

export function GetPeerInfo() {
  return window['go']['app']['App']['GetPeerInfo']();
}

export function IsLoggedIn() {
  return window['go']['app']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['app']['App']['Register'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
