// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1) {
  return window['go']['main']['App']['AcceptFriendRequest'](arg1);
}

export function ConnectToPeer(arg1) {
  return window['go']['main']['App']['ConnectToPeer'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetFriendRequests() {
  return window['go']['main']['App']['GetFriendRequests']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetMultiaddr() {
  return window['go']['main']['App']['GetMultiaddr']();
}

export function GetPeerInfo() {
  return window['go']['main']['App']['GetPeerInfo']();
}

export function GetUnreadCount() {
  return window['go']['main']['App']['GetUnreadCount']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RejectFriendRequest(arg1) {
  return window['go']['main']['App']['RejectFriendRequest'](arg1);
}

export function SendFriendRequest(arg1, arg2) {
  return window['go']['main']['App']['SendFriendRequest'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
