// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1:string):Promise<void>;

export function ConnectToPeer(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetFriendRequests():Promise<Array<Record<string, any>>>;

export function GetFriends():Promise<Array<Record<string, any>>>;

export function GetMessages(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetMultiaddr():Promise<string>;

export function GetPeerInfo():Promise<string>;

export function GetUnreadCount():Promise<number>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RejectFriendRequest(arg1:string):Promise<void>;

export function SendFriendRequest(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
