// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetMultiaddr():Promise<string>;

export function GetPeerInfo():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;
